#+title: Main
#+author: Cameron W Pittman
#+email: cameronp@mit.edu
#+export_file_name: Pittman-SM.pdf

#+options: author:nil
#+options: date:nil
#+options: email:nil
#+options: title:nil
#+options: toc:nil

# adds hanging-indent and extra line breaks to <bibliography />
# see https://docs.citationstyles.org/en/stable/specification.html
#+cite_export: csl ieee-modded.csl

# adapted from the unofficial MIT thesis template: https://www.overleaf.com/latex/templates/mit-thesis-template/ytphktgwpktc
# see also an example of compiling multiple org files into a thesis: https://github.com/dangom/org-thesis

# IMPORTANT: The official thesis specifications are available at:
#            http://libraries.mit.edu/archives/thesis-specs/
#
#            Please verify your thesis' formatting and copyright
#            assignment before submission. If you notice any
#            discrepancies between these templates and the
#            MIT Libraries' specs, please let us know
#            by e-mailing thesis@mit.edu

#+begin_export tex
%% The documentclass options along with the pagestyle can be used to generate
%% a technical report, a draft copy, or a regular thesis. You may need to
%% re-specify the pagestyle after you \include cover.tex. For more
%% information, see the first few lines of mitthesis.cls.
%%
%\documentclass[12pt,vi,twoside]{mitthesis}
%%
%%  If you want your thesis copyright to you instead of MIT, use the
%%  ``vi'' option, as above.
%%
%\documentclass[12pt,twoside,leftblank]{mitthesis}
%%
%% If you want blank pages before new chapters to be labelled ``This
%% Page Intentionally Left Blank'', use the ``leftblank'' option, as
%% above.
#+end_export

#+latex_class: mitthesis
#+latex_class_options: [10pt,leftblank,twoside]

#+latex_header: \usepackage{lgrind}

#+begin_export tex
%% These have been added at the request of the MIT Libraries, because
%% some PDF conversions mess up the ligatures.  -LB, 1/22/2014
#+end_export
#+latex_header: \usepackage{cmap}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \pagestyle{plain}

# my packages
#+latex_header: \usepackage{algorithm2e}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{minted}

#+begin_export tex
%% This bit allows you to either specify only the files which you wish to
%% process, or `all' to process all files which you \include.
%% Krishna Sethuraman (1990).

%\typein [\files]{Enter file names to process, (chap1,chap2 ...), or `all' to process all files:}
#+end_export
#+latex_header: \def\all{all}
#+latex_header: \ifx\files\all \typeout{Including all files.} \else
#+begin_export tex
%\typeout{Including only \files.} \includeonly{\files} \fi
#+end_export

# you could set (setq org-latex-with-hyperref nil) first to avoid two \hypersetup blocks in the
# compiled .tex file...
# ...but it's not necessary because the block below is defined second and will be the one that gets
# picked up in the finished PDF file
#+begin_export tex
\hypersetup{
  pdfauthor={Cameron W. Pittman},
  pdftitle={Distributed Multi-Agent Decision Making Under Uncertain Communication},
  pdfkeywords={},
  pdfsubject={},
  pdfcreator={Emacs 28.2 (Org mode 9.6)},
  pdflang={English}}
#+end_export

# code styles. see https://pygments.org/styles/
# - default :: can't go wrong here!
# - tango :: nice, but the greens and blues are a little garish
# - trac :: good for lisp bc parens are a different color than text
# - vs :: helpful colors that aren't garish
#+begin_export tex
\usemintedstyle[lisp]{vs}
#+end_export

#+include: "0-cover.org"

# custom commands and styles
#+begin_export tex
\newcommand{\edge}[3]{#1 \xrightarrow{#3} #2}
\newcommand{\conedge}[3]{#1 \xRightarrow{#3} #2}
\newcommand{\gammabar}{\bar{\gamma}}
%\newcommand{\obs}{\texttt{obs}}
\newcommand{\obs}{\psi}
\newcommand{\assign}{\xi}

\newcommand{\finalversion}[1]{}

\newtheorem{theorem}{Theorem}[]
\newtheorem{corollary}{Corollary}[theorem]
\newtheorem{lemma}[theorem]{Lemma}

\newtheorem{transformation}{Transformation}

\theoremstyle{definition}
\newtheorem{defn}{Definition}

\theoremstyle{definition}
\newtheorem{example}{Example}
#+end_export

# TOC, figures, and tables
#+begin_export tex
\pagestyle{plain}

\tableofcontents
\newpage
\listoffigures
\newpage
\renewcommand\listoflistingscaption{List of source codes}
\listoflistings
\newpage
\listoftables

\begin{document}
#+end_export

#+include: "1-introduction.org"
#+include: "2-problem-statement.org"
#+include: "3-approach.org"
#+include: "4-technical-vdc.org"
#+include: "5-technical-scheduling.org"
#+include: "6-technical-coordination.org"
#+include: "7-technical-architecture.org"
#+include: "8-evaluation.org"
#+include: "9-discussion.org"

#+begin_export tex
\appendix
#+end_export

# insert appendices here

#+begin_export tex
%% This defines the bibliography file (main.bib) and the bibliography style.
%% If you want to create a bibliography file by hand, change the contents of
%% this file to a `thebibliography' environment.  For more information
%% see section 4.3 of the LaTeX manual.
\bibliography{extra-citations}
\begin{singlespace}
\begin{thebibliography}
#+end_export

# use org-cite
#+print_bibliography:

#+begin_export tex
\end{thebibliography}
\end{singlespace}
\end{document}
#+end_export

