#+title: Notes

* TODO "communication uncertainty" vs "observation uncertainty" vs "observation delay"
We should be consistent. At the very least, include a note somewhere towards the beginning that the
terms are largely interchangeable
* TODO need more flexibility in referring to control programs in RMPL
comment on this in discussion
* TODO controllable vs free vs requirement; contingent vs uncontrollable
Need to be more consistent / or just explain the (lack of) diff somewhere
* TODO can we do optimistic rewriting when we receive an event with infinite obs delay too?
might only be useful in the case of a gammabar with a finite lower bound and infinite upper bound
(Lemma 2). not useful for Lemma 3

does the rewriting math actually work though with the infinity?
* TODO did I use periods with bullet points correctly?
* TODO Something about the fact that we have a "least commitment" dispatcher
[cite:@Stedl2004] references it on pg 49
* TODO when do we reference VDC first? make sure there aren't a bunch of (VDC) introduction of acronyms
* TODO mitmproxy links
- https://hub.docker.com/r/mitmproxy/mitmproxy/
- https://mitmproxy.org/
- https://github.com/KevCui/mitm-scripts#mitm-delay-request
- https://stackoverflow.com/questions/47827496/how-to-configure-docker-container-proxy
- https://docs.docker.com/network/proxy/
