#+title: Abstract

# 1. Argument for thesis
#  1. lay out paper structure with one sentence per each below
#    Structure
#  2. Fulfilling important need
#  3. looked at relevant SOTA
#  4. identified the gap
#  5. my key insight that will close the gap. and why it's innovative
#     1. why is it hard or not?
#  6. and my approach
#  7. identify benchmarks to evaluate whether we closed the gap
#     1. measurables
#     2. how to compare to SOTA
#     3. quantify the benefit
#  8. x for y. how we fulfill the need

As space exploration accelerates and the number of robots and humans working in extreme environments
grows with it, we must enact autonomous multi-agent coordination in order to safely operate in
environments that are inherently hostile to communication. To the best of our knowledge, there are
no multi-agent scheduling algorithms capable of independently reasoning over communication delay. A
key gap that must be addressed is a single-agent scheduler capable of deciding when to act given
uncertain observation, which can the form the basis for distributed multi-agent scheduling. Existing
research has provided insights into temporal reasoning, namely modeling observation uncertainty and
scheduling events with temporal constraints. There is both a need for deciding when to schedule
events when there is uncertain observation delay, and a need to robustly coordinate between agents.
Scheduling events in the face of uncertainty is a challenge due to the compounding uncertainties of
uncontrollable exogenous events, unknown observation delay, and uncertain communication between
agents. This thesis puts forth a series of contributions that culminates in the demonstration of a
robust single-agent task executive that used our scheduler to coordinate in a multi-agent context
despite observation delay. Doing so required insights in checking controllability of temporal
constraints with uncertain delay, defining a scheduler that is robust to uncertain observation
delay, integrating the scheduler in an existing high-level task executive, and a coordination
strategy for multiple agents. We show that the scheduler exhibits the expected performance
characteristics, and perform laboratory demonstrations of multi-agent execution with uncertain
communication using a scenario inspired by human spaceflight.
